# Generated by Django 4.1.3 on 2022-11-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
