# Generated by Django 4.1.3 on 2022-11-20 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_recruiter_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiter',
            name='status',
        ),
    ]
